name: Go Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'  # Set this to the Go version your project uses

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up environment variable
        run: echo "CI_SQS_PRICING_TEST=true" >> $GITHUB_ENV

      - name: Run Go test
        run: go test -timeout 30s -run TestTokensUseCaseTestSuite/TestGetPrices_Chain_FindUnsupportedTokens github.com/osmosis-labs/sqs/tokens/usecase -v -count=1