name: Pricing Test

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
      - "v[0-9]**"

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'  # Set this to the Go version your project uses

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

  pricing_test:
      - name: Set up environment variable
        run: echo "CI_SQS_PRICING_TEST=true" >> $GITHUB_ENV

      - name: Run Go test
        run: go test -timeout 30s -run TestTokensUseCaseTestSuite/TestGetPrices_Chain_FindUnsupportedTokens github.com/osmosis-labs/sqs/tokens/usecase -v -count=1

  routes_test:
    - name: Set up environment variable
      run: echo "CI_SQS_ROUTE_TEST=true" >> $GITHUB_ENV

    - name: Run Go test
      run: go test -timeout 30s -run TestRouterTestSuite/TestGetCandidateRoutes_Chain_FindUnsupportedRoutes github.com/osmosis-labs/sqs/router/usecase -count=1 -v