name: Setup Go Environment
on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}

      - name: Check out code
        uses: actions/checkout@v2
